### ISSUE TITLE
Getting ExistentialError error when typing the key in function argument

### ISSUE THREAD

**Issue by gohm-tech** [osvenskan/sysv_ipc#15]
Hi,
When we set the arguments like below we are getting ExistentialError : "No queue exists with the specified key"
`sender_queue = sysv_ipc.MessageQueue(key=content["queue_key"], mode=(sysv_ipc.IPC_CREAT | int('0666', 8)))`

But when we use it like this, it is working.

`sender_queue = sysv_ipc.MessageQueue(content["queue_key"], (sysv_ipc.IPC_CREAT | int('0666', 8)))`

Are there any errors? Are we overlooking something? Why don't we get an error that there is an error with the arguments? Is this a correct type of error? Because it took some time to find the right way.

**Comment by osvenskan** [comment]
I see the same behavior; it's a bug. I'll look into it. Thanks for the clear bug report.

**Comment by osvenskan** [comment]
@gohm-tech Ooops, I overlooked the same thing you did. 😃 I think `sysv_ipc` is behaving correctly. Your call uses `sysv_ipc.IPC_CREAT`, but it's passing it to the `mode` argument. `mode` is strictly for unix-style permission bits. `IPC_CREAT`, `IPC_EXCL`, and `IPC_CREX` have to be passed in the `flags` argument. So this call --

```python
sysv_ipc.MessageQueue(key=content["queue_key"], mode=(sysv_ipc.IPC_CREAT | int('0666', 8)))
```

is the same as this --

```python
sysv_ipc.MessageQueue(key=content["queue_key"], flags=0, mode=int('0666', 8))
```

As it says in the documentation --

> With `flags` set to the **default** of 0, the module attempts to **open an existing** message queue identified by `key` and raises a `ExistentialError` if it doesn't exist. 

Apparently there's no message queue with key = `content["queue_key"]` when you run your code, and `sysv_ipc` correctly reports that. 

Your alternate version works, but it's still confused --

```python
sysv_ipc.MessageQueue(content["queue_key"], (sysv_ipc.IPC_CREAT | int('0666', 8)))
```

That's equivalent to 

```python
sysv_ipc.MessageQueue(key=content["queue_key"], flags=(sysv_ipc.IPC_CREAT | int('0666', 8)))
```

The `int('0666', 8)` bits in the `flags` argument are ignored, so that is the same as this -- 

```python
sysv_ipc.MessageQueue(key=content["queue_key"], flags=sysv_ipc.IPC_CREAT)
```

**Here's what you probably want --**

```python
sysv_ipc.MessageQueue(key=content["queue_key"], flags=sysv_ipc.IPC_CREAT, mode=int('0666', 8))
```
